### ISSUE TITLE
How to use `asciidoctor-reducer` on GitHub itself?

### ISSUE THREAD

**Issue by Mo-Gul** [asciidoctor/asciidoctor-reducer#46]
Sorry, this is not an issue per se. I stranded here after following the links given in https://github.com/asciidoctor/asciidoctor/issues/1088#issuecomment-87685739.

My question is, how to use `asciidoctor-reducer` to solve the problem that `include::`s are not expanded on GitHub? Optimally there would be a GitHub Action to do the job. If that would be possible, is there already an Action (I couldn't find one)? If not, what would be the steps to do?

Please note that I just started using AsciiDoctor. So a description for dummies would be welcome ;)

Many thanks in advance for your answer!!!

**Comment by hans-d** [comment]
see https://github.com/github/markup/issues/1095
it gives an example: https://github.com/r2d2bzh/docker-build-nodejs/blob/848e41ba6249de933816bce29400606594871e59/.github/workflows/readme.yaml

**Comment by mojavelinux** [comment]
Thanks for providing that example Hans! I'd be happy to add this little trick to the README.

**Comment by mojavelinux** [comment]
I've submitted a PR based on this suggestion. See #47.
