### ISSUE TITLE
`ifdef` statements seem to be gobbled by the `reduce-readme.yml`

### ISSUE THREAD

**Issue by Mo-Gul** [asciidoctor/asciidoctor-reducer#50]
at least this is the case for the given example workflow code.

I tested this at <https://github.com/Mo-Gul/asciidoctor-reducer-test>.

**Comment by mojavelinux** [comment]
From my test, it works exactly as it is designed to work. When you run asciidoctor-reducer on docs/README-source.adoc in that repository, the ifdef preprocessor conditional is removed from the output file.

If you can prove something is not working as expected, please provide a test.

**Comment by Mo-Gul** [comment]
This seems to be my fault as well. Using `run: asciidoctor-reducer --preserve-conditionals ...` in the workflow gives the expected result.

**Comment by mojavelinux** [comment]
I added a note about `--preserve-conditionals` to the code snippet.
