### ISSUE TITLE
Handling of built-in asciidoctor attributes

### ISSUE THREAD

**Issue by AlexB3ll** [asciidoctor/asciidoctor-reducer#56]
When using Asciidoctor, it's possible to specify the backend e.g. `--backend pdf`. It's then possible to use defines to control the behaviour between different backends using the built-in attributes e.g. `ifdef::backend-pdf[]`. However, asciidoctor-reducer has no concept of a backend and therefore these attributes don't exist.

Is it possible to preserve only these conditionals?

My current solution is to run asciidoctor-reducer once per backend, manually setting the corresponding attribute each time.

**Comment by mojavelinux** [comment]
> My current solution is to run asciidoctor-reducer once per backend, manually setting the corresponding attribute each time.

That's one correct approach. The other approach is to instruct reducer to preserve the conditionals when it runs.

In the future, please ask questions about usage in the project chat at https://chat.asciidoctor.org. The issue tracker is not a support portal.
